# -*- mode: ruby -*-
# vi: set ft=ruby :

$install_puppet = <<-PUPPET
sudo apt-get update -y
sudo apt-get install -y puppet
PUPPET

Vagrant.configure("2") do |config|

  config.vm.define "puppetServer" do |puppetServer|

    puppetServer.vm.box = "bento/ubuntu-20.04"
    puppetServer.vm.hostname = "puppetServer"
    puppetServer.vm.network :private_network, ip: "192.168.90.3"

    # Primer aprovisionamiento: instalar Puppet con shell
    puppetServer.vm.provision "shell", inline: $install_puppet

    # Segundo aprovisionamiento: ejecutar Puppet con manifiestos
    puppetServer.vm.provision :puppet do |puppet|
      puppet.manifests_path = "puppet/manifests"
      puppet.manifest_file  = "site.pp"
      puppet.module_path    = "puppet/modules"
    end
  end 

end